-- switch case demo
DECLARE
N NUMBER := 3;
BEGIN
	CASE N
		WHEN 1 THEN
			DBMS_OUTPUT.PUT_LINE('NUMBER IS 1');
		WHEN 2 THEN
			DBMS_OUTPUT.PUT_LINE('NUMBER IS 2');
		ELSE
			DBMS_OUTPUT.PUT_LINE('INVALID!!');
	END CASE;
END;
/